// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Products.Infrastructure.Context;

#nullable disable

namespace Products.Infrastructure.Migrations
{
    [DbContext(typeof(ProductContext))]
    partial class ProductContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Products.Domin.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("BannerUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("https://via.placeholder.com/500x100.png");

                    b.Property<DateTime>("CreationDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("https://via.placeholder.com/85.png");

                    b.Property<DateTime?>("ModificationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("https://via.placeholder.com/150.png");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Products.Domin.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("https://via.placeholder.com/150x150.png");

                    b.Property<DateTime>("CreationDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTime?>("ModificationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CategoryId = 2,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "گوشی موبایل سامسونگ مدل Galaxy S21",
                            Price = 20000m,
                            Title = "گوشی موبایل سامسونگ"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CategoryId = 3,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "لپ‌تاپ ایسوس مدل ZenBook Pro",
                            Price = 30000m,
                            Title = "لپ‌تاپ ایسوس"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CategoryId = 4,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "کیبورد گیمینگ برند ریزر مدل BlackWidow",
                            Price = 5000m,
                            Title = "کیبورد گیمینگ"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CategoryId = 4,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "کامپیوتر رومیزی برند Dell مدل XPS",
                            Price = 40000m,
                            Title = "کامپیوتر رومیزی Dell"
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            CategoryId = 5,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "یخچال سامسونگ مدل Side by Side",
                            Price = 15000m,
                            Title = "یخچال سامسونگ"
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            CategoryId = 2,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "گوشی موبایل آیفون 13 با پردازنده A15 Bionic",
                            Price = 25000m,
                            Title = "گوشی موبایل آیفون 13"
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            CategoryId = 3,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "لپ‌تاپ اپل مک‌بوک پرو 16 اینچ",
                            Price = 35000m,
                            Title = "لپ‌تاپ اپل مک‌بوک پرو"
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            CategoryId = 2,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "تبلت اپل آیپد پرو 12.9 اینچ",
                            Price = 22000m,
                            Title = "تبلت آیپد پرو"
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            CategoryId = 4,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "مانیتور 4K برند سامسونگ مدل U32J590",
                            Price = 8000m,
                            Title = "مانیتور 4K سامسونگ"
                        },
                        new
                        {
                            Id = 10,
                            Active = true,
                            CategoryId = 4,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "ماوس گیمینگ ریزر مدل DeathAdder",
                            Price = 1500m,
                            Title = "ماوس گیمینگ ریزر"
                        },
                        new
                        {
                            Id = 11,
                            Active = true,
                            CategoryId = 5,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "ماشین لباسشویی بوش مدل Serie 8",
                            Price = 12000m,
                            Title = "ماشین لباسشویی بوش"
                        },
                        new
                        {
                            Id = 12,
                            Active = true,
                            CategoryId = 5,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "یخچال ساید بای ساید ال‌جی مدل GR-B247JDS",
                            Price = 18000m,
                            Title = "یخچال ساید بای ساید ال‌جی"
                        },
                        new
                        {
                            Id = 13,
                            Active = true,
                            CategoryId = 3,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "لپ‌تاپ اچ‌پی مدل Spectre x360",
                            Price = 33000m,
                            Title = "لپ‌تاپ اچ‌پی"
                        },
                        new
                        {
                            Id = 14,
                            Active = true,
                            CategoryId = 1,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "دوربین دیجیتال کانن مدل EOS 90D",
                            Price = 12000m,
                            Title = "دوربین دیجیتال کانن"
                        },
                        new
                        {
                            Id = 15,
                            Active = true,
                            CategoryId = 1,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "پاور بانک انکر مدل PowerCore 10000",
                            Price = 1200m,
                            Title = "پاور بانک انکر"
                        },
                        new
                        {
                            Id = 16,
                            Active = true,
                            CategoryId = 1,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "هارد اکسترنال وسترن دیجیتال مدل My Passport",
                            Price = 2500m,
                            Title = "هارد اکسترنال وسترن دیجیتال"
                        },
                        new
                        {
                            Id = 17,
                            Active = true,
                            CategoryId = 1,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "اسپیکر بلوتوثی جی‌بی‌ال مدل Flip 5",
                            Price = 3500m,
                            Title = "اسپیکر بلوتوثی جی‌بی‌ال"
                        });
                });

            modelBuilder.Entity("Products.Domin.Entities.Category", b =>
                {
                    b.HasOne("Products.Domin.Entities.Category", "ParentCategory")
                        .WithMany("Children")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Products.Domin.Entities.Product", b =>
                {
                    b.HasOne("Products.Domin.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Products.Domin.Entities.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
